### ISSUE TITLE
Table view gestures breaking in iOS 11

### ISSUE THREAD

**Issue by cnstoll** [SwipeCellKit/SwipeCellKit#56] opened 2017-06-25 16:41 UTC
Hi,

I'm noticing strange behavior after the Extensions method "setGestureEnabled" gets called in iOS 11. It seems to break all tap gesture recognition in iOS 11. It looks like commenting this out fixes the issue for now...and doesn't actually seem to break anything in iOS 10.

Just reporting this as additional info for the betas.

Btw, your library is great. I'll most likely continue using it, even though iOS 11 provides similar functionality. I've liked it a lot.

Thanks,

- Conrad

**Comment by kurabi** [comment] 2017-06-26 18:04
Thanks @cnstoll. Noted.

**Comment by ezar** [comment] 2017-06-28 06:18
+1

**Comment by eltonf** [comment] 2017-07-07 12:33
@cnstoll thanks for the suggestion, it works for me too. I only disable setGestureEnabled for iOS 11 to leave all iOS 10 functionality intact. As far as I can tell it still works identically in iOS 10 and iOS 11. Maybe the main developer can explain why this method was ever needed.

```
    func setGestureEnabled(_ enabled: Bool) {
        if #available(iOS 11, *) {
            // Workaround for iOS 11+, do nothing
        } else {
            gestureRecognizers?.forEach {
                guard $0 != panGestureRecognizer else { return }
                
                $0.isEnabled = enabled
            }
        }
    }
```

**Comment by fishcharlie** [comment] 2017-07-16 22:34
This looks like a duplicate of #48

**Closed** 2017-07-25 21:13 UTC
Labels: duplicate
