### ISSUE TITLE
left, I return nil, and the left will appear a blank.  (version 2.4.2)

### ISSUE THREAD

**Issue by daishuyi** [SwipeCellKit/SwipeCellKit#216] opened 2018-06-14 08:52 UTC

**Comment by daishuyi** [comment] 2018-06-14 08:53
![1528965196691](https://user-images.githubusercontent.com/38234719/41401806-5ee21ff2-6ff3-11e8-9642-6be8049584f4.jpg)

**Comment by daishuyi** [comment] 2018-06-14 08:54
I download 2.4.2, and only make right actions appear. 
[SwipeCellKit-2.4.2.zip](https://github.com/SwipeCellKit/SwipeCellKit/files/2101526/SwipeCellKit-2.4.2.zip)

**Comment by daishuyi** [comment] 2018-06-14 09:33
I download the 2.4.2 code, and only make the right actions appear
[SwipeCellKit-2.4.2.zip](https://github.com/SwipeCellKit/SwipeCellKit/files/2101672/SwipeCellKit-2.4.2.zip)

**Comment by kurabi** [comment] 2018-06-14 18:59
Duplicate of #215

**Closed by kurabi** 2018-06-14 18:59 UTC
